after_success:
  - npm run coveralls
  - npm run codecov
before_script:
  - psql -c 'drop database if exists taps_test;' -U postgres
  - psql -c 'create database taps_test;' -U postgres
  - psql -c "CREATE USER andela_teams_user1 WITH PASSWORD 'andela_teams_user1_password';" -U postgres
email: false
env:
  global:
    - export NODE_ENV=test
install:
  - npm install
language: node_js
node_js:
  - "8"
script: npm test
services:
  - postgresql
